### ISSUE TITLE
Will this lib be updated

### ISSUE THREAD

**Issue by feast107** [balazsbotond/eslinq#1]
I'm right now working on porting `LINQ` to TS/JS, and will continuing update. And I m looking for a package name to publish on `npm` which will be simple and clear. Will I have any possible to use this name `eslinq` to publish, I'm looking forward your reply. 😸

**Comment by feast107** [comment]
By the way, C# is really an elegant language that I guess the reason why we all trying to port it. I dont know whether u notice C# has won the programming language of the year award on [TIBOE](https://www.tiobe.com/tiobe-index/). Thats inspiring

**Comment by balazsbotond** [comment]
Hi, I'm not planning to update it in any way. It was a nice experiment but I guess it's time to archive it. I've taken a look at your lib and it looks promising.

The npm package isn't really used by anybody as far as I can see.I'm not familiar with how npm package names are transferred (of if it is even possible at all), and I have no time to research it right now but I'd be happy to transfer it if there isn't a lot of work involved on my part. Could you please do a bit of research on the best way of doing the transfer and summarize what you find here?

**Comment by feast107** [comment]
I m very appreciated to have your reply. 🌞  I v found on the official website of `npm` about guidance of [transferring-a-package-from-a-user-account-to-another-user-account](https://nodejs.cn/npm/packages-and-modules/updating-and-managing-your-published-packages/transferring-a-package-from-a-user-account-to-another-user-account/) through `web-ui` or `cmd`. These procedures seems not to be complex.
Here is my npm account [feast107](https://www.npmjs.com/~feast107). I m glad to provide if u need any other information.

**Comment by feast107** [comment]
Oops I made a mistake, it was the translated page. Source docs is in [transferring-a-package-from-a-user-account-to-another-user-account](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account)
